import * as vscode from 'vscode'
import { StatusBarItem } from 'vscode'

import { EXTENSION_NAME } from '../env'

export enum LineState {
  NO_FILE_SELECTED_ERROR = 'no-file-selected-error',
  LOADING = 'loading',
  AI = 'ai',
  HUMAN = 'human',
  TAB_AUTOCOMPLETE = 'tab-autocomplete',
  NO_ATTRIBUTION_DATA = 'no-attribution-data',
  ATTRIBUTION_ERROR = 'attribution-error',
  BLAME_DIRTY = 'blame-dirty',
  BLAME_NOT_COMMITTED = 'blame-not-committed',
  BLAME_ERROR = 'blame-error',
  AUTH_REQUIRED = 'auth-required',
  AUTH_PENDING = 'auth-pending',
}

export type IView = {
  /**
   * Refresh the view.
   */
  refresh(state: LineState): void

  /**
   * Display an error message in the view.
   */
  error(message: string): void

  /**
   * Set auth pending state.
   */
  setAuthPending(loginUrl: string): void

  /**
   * Clear auth pending state.
   */
  clearAuthPending(): void
}

const STATUS_PREFIX = EXTENSION_NAME.endsWith('-dev')
  ? 'Tracy (DEV): '
  : 'Tracy: '

export class StatusBarView implements IView {
  private isAuthPending = false
  private authPendingUrl?: string

  constructor(private statusBarItem: StatusBarItem) {
    this.statusBarItem.text = STATUS_PREFIX
    this.statusBarItem.command = `${EXTENSION_NAME}.showInfoPanel`
    this.refresh(LineState.NO_FILE_SELECTED_ERROR)
  }
  refresh(state: LineState): void {
    // Don't allow refresh to override auth pending state
    if (this.isAuthPending && state !== LineState.AUTH_PENDING) {
      return
    }

    let markdown: string = ''
    switch (state) {
      case LineState.NO_FILE_SELECTED_ERROR:
        this.statusBarItem.text = `${STATUS_PREFIX}$(error)`
        markdown =
          'No file selected. Please open a file to get AI attribution data.'
        break
      case LineState.LOADING:
        this.statusBarItem.text = `${STATUS_PREFIX}$(loading~spin)`
        break
      case LineState.AI:
        this.statusBarItem.text = `${STATUS_PREFIX}$(robot)`
        markdown = 'Detected AI-generated code on this line'
        break
      case LineState.HUMAN:
        this.statusBarItem.text = `${STATUS_PREFIX}$(person)`
        markdown = 'Detected human-written code on this line'
        break
      case LineState.TAB_AUTOCOMPLETE:
        this.statusBarItem.text = `${STATUS_PREFIX}$(robot)`
        markdown =
          'Detected code generated by an AI-powered code completion tool on this line'
        break
      case LineState.NO_ATTRIBUTION_DATA:
        this.statusBarItem.text = `${STATUS_PREFIX}$(dash)`
        markdown = 'No AI attribution data for this line'
        break
      case LineState.ATTRIBUTION_ERROR:
        this.statusBarItem.text = `${STATUS_PREFIX}$(error)`
        markdown =
          'Error retrieving AI attribution data for this line. Please try again.'
        break
      case LineState.BLAME_DIRTY:
        this.statusBarItem.text = `${STATUS_PREFIX}$(warning)`
        markdown =
          'File has unsaved changes. Please save the file to get accurate AI attribution data.'
        break
      case LineState.BLAME_NOT_COMMITTED:
        this.statusBarItem.text = `${STATUS_PREFIX}$(warning)`
        markdown =
          'Line is not yet committed. Please commit the changes to get accurate AI attribution data.'
        break
      case LineState.BLAME_ERROR:
        this.statusBarItem.text = `${STATUS_PREFIX}$(error)`
        markdown =
          'Error retrieving git blame information. Please ensure the repository is accessible.'
        break
      case LineState.AUTH_REQUIRED:
        this.statusBarItem.text = `${STATUS_PREFIX}$(error)`
        markdown = 'Authentication required.'
        break
      default:
        this.statusBarItem.text = `${STATUS_PREFIX}$(dash)`
    }

    if (state !== LineState.AUTH_PENDING) {
      this.statusBarItem.command = `${EXTENSION_NAME}.showInfoPanel`
      this.statusBarItem.backgroundColor = undefined
    }
    const fullMarkdown = this.generateMarkdown(markdown)
    const markdownString = new vscode.MarkdownString(fullMarkdown)
    markdownString.isTrusted = true // Enable command links
    markdownString.supportHtml = true // Enable HTML for better formatting
    this.statusBarItem.tooltip = markdownString
    this.statusBarItem.show()
  }

  error(message: string): void {
    this.statusBarItem.text = `${STATUS_PREFIX}$(error)`
    const fullMarkdown = this.generateMarkdown(message)
    const markdownString = new vscode.MarkdownString(fullMarkdown)
    markdownString.isTrusted = true // Enable command links
    markdownString.supportHtml = true // Enable HTML for better formatting
    this.statusBarItem.tooltip = markdownString
    this.statusBarItem.show()
  }

  /**
   * Set auth pending state - this state cannot be overridden by regular refresh calls
   */
  setAuthPending(loginUrl: string): void {
    this.isAuthPending = true
    this.authPendingUrl = loginUrl
    this.refresh(LineState.AUTH_PENDING)
  }

  /**
   * Clear auth pending state and return to normal operation
   */
  clearAuthPending(): void {
    this.isAuthPending = false
    this.authPendingUrl = undefined
    this.statusBarItem.backgroundColor = undefined
    this.refresh(LineState.NO_FILE_SELECTED_ERROR)
  }

  private generateMarkdown(context: string | null): string {
    let markdown = ['## Mobb Tracy', '', 'AI Code Attribution']
    if (context) {
      markdown = markdown.concat(['', '---', '', context])
    }
    return markdown.join('\n')
  }
}
